<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Equipo 1: Víctor Ochoa y Salvador Rodríguez">

<title>Análisis Predictivo de Rendimiento Estudiantil</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="ReporteProyect_VF_files/libs/clipboard/clipboard.min.js"></script>
<script src="ReporteProyect_VF_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="ReporteProyect_VF_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="ReporteProyect_VF_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="ReporteProyect_VF_files/libs/quarto-html/popper.min.js"></script>
<script src="ReporteProyect_VF_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ReporteProyect_VF_files/libs/quarto-html/anchor.min.js"></script>
<link href="ReporteProyect_VF_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ReporteProyect_VF_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ReporteProyect_VF_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ReporteProyect_VF_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ReporteProyect_VF_files/libs/bootstrap/bootstrap-4d7f0bce1131f3e5f9547cd857cfbfc8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="ReporteProyect_VF_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="ReporteProyect_VF_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción">Introducción</a></li>
  <li><a href="#business-understanding" id="toc-business-understanding" class="nav-link" data-scroll-target="#business-understanding">Business understanding</a></li>
  <li><a href="#data-understanding" id="toc-data-understanding" class="nav-link" data-scroll-target="#data-understanding">Data understanding</a>
  <ul class="collapse">
  <li><a href="#descripción-del-conjunto-de-datos" id="toc-descripción-del-conjunto-de-datos" class="nav-link" data-scroll-target="#descripción-del-conjunto-de-datos">Descripción del Conjunto de Datos</a></li>
  </ul></li>
  <li><a href="#análisis-exploratorio-de-datos-eda" id="toc-análisis-exploratorio-de-datos-eda" class="nav-link" data-scroll-target="#análisis-exploratorio-de-datos-eda">Análisis Exploratorio de Datos (EDA)</a>
  <ul class="collapse">
  <li><a href="#varibale-g3-sin-ser-binaria" id="toc-varibale-g3-sin-ser-binaria" class="nav-link" data-scroll-target="#varibale-g3-sin-ser-binaria">Varibale <span class="math inline">\(G3\)</span> sin ser binaria</a>
  <ul class="collapse">
  <li><a href="#análisis-univariado-de-la-variable-objetivo-textg3" id="toc-análisis-univariado-de-la-variable-objetivo-textg3" class="nav-link" data-scroll-target="#análisis-univariado-de-la-variable-objetivo-textg3">Análisis Univariado de la Variable Objetivo (<span class="math inline">\(\text{G3}\)</span>)</a></li>
  <li><a href="#análisis-bivariado-factores-numéricos-vs.-textg3" id="toc-análisis-bivariado-factores-numéricos-vs.-textg3" class="nav-link" data-scroll-target="#análisis-bivariado-factores-numéricos-vs.-textg3">Análisis Bivariado: Factores Numéricos vs.&nbsp;<span class="math inline">\(\text{G3}\)</span></a></li>
  <li><a href="#relaciones-gráficas-de-factores-clave-vs.-textg3" id="toc-relaciones-gráficas-de-factores-clave-vs.-textg3" class="nav-link" data-scroll-target="#relaciones-gráficas-de-factores-clave-vs.-textg3">Relaciones Gráficas de Factores Clave vs.&nbsp;<span class="math inline">\(\text{G3}\)</span></a></li>
  <li><a href="#análisis-bivariado-factores-categóricos-vs.-textg3" id="toc-análisis-bivariado-factores-categóricos-vs.-textg3" class="nav-link" data-scroll-target="#análisis-bivariado-factores-categóricos-vs.-textg3">Análisis Bivariado: Factores Categóricos vs.&nbsp;<span class="math inline">\(\text{G3}\)</span></a></li>
  <li><a href="#respuesta-preliminar-a-las-preguntas-de-business-understanding" id="toc-respuesta-preliminar-a-las-preguntas-de-business-understanding" class="nav-link" data-scroll-target="#respuesta-preliminar-a-las-preguntas-de-business-understanding">Respuesta preliminar a las preguntas de Business understanding</a></li>
  </ul></li>
  <li><a href="#analisis-eda-para-varibale-g3-binaria." id="toc-analisis-eda-para-varibale-g3-binaria." class="nav-link" data-scroll-target="#analisis-eda-para-varibale-g3-binaria.">Analisis EDA para varibale <span class="math inline">\(G3\)</span> binaria.</a></li>
  </ul></li>
  <li><a href="#modelado-y-evaluacion." id="toc-modelado-y-evaluacion." class="nav-link" data-scroll-target="#modelado-y-evaluacion.">Modelado y evaluacion.</a>
  <ul class="collapse">
  <li><a href="#preparación-de-la-base-de-datos-para-el-modelaje." id="toc-preparación-de-la-base-de-datos-para-el-modelaje." class="nav-link" data-scroll-target="#preparación-de-la-base-de-datos-para-el-modelaje.">1. Preparación de la base de datos para el modelaje.</a></li>
  <li><a href="#selección-de-variables-relevantes-para-el-status-de-un-estudiante" id="toc-selección-de-variables-relevantes-para-el-status-de-un-estudiante" class="nav-link" data-scroll-target="#selección-de-variables-relevantes-para-el-status-de-un-estudiante">2. Selección de Variables Relevantes para el Status de un Estudiante</a>
  <ul class="collapse">
  <li><a href="#métodos-de-selección" id="toc-métodos-de-selección" class="nav-link" data-scroll-target="#métodos-de-selección">Métodos de selección</a></li>
  <li><a href="#resultados-del-análisis-de-importancia" id="toc-resultados-del-análisis-de-importancia" class="nav-link" data-scroll-target="#resultados-del-análisis-de-importancia">Resultados del Análisis de Importancia</a></li>
  </ul></li>
  <li><a href="#modelado-evaluación-de-4-casos" id="toc-modelado-evaluación-de-4-casos" class="nav-link" data-scroll-target="#modelado-evaluación-de-4-casos">3. Modelado: Evaluación de 4 Casos</a>
  <ul class="collapse">
  <li><a href="#caso-1-todas-las-variables-sin-balanceo" id="toc-caso-1-todas-las-variables-sin-balanceo" class="nav-link" data-scroll-target="#caso-1-todas-las-variables-sin-balanceo">Caso 1: Todas las Variables / Sin Balanceo</a></li>
  <li><a href="#caso-2-todas-las-variables-con-balanceo-up-sampling" id="toc-caso-2-todas-las-variables-con-balanceo-up-sampling" class="nav-link" data-scroll-target="#caso-2-todas-las-variables-con-balanceo-up-sampling">Caso 2: Todas las Variables / Con Balanceo (Up-Sampling)</a></li>
  <li><a href="#caso-3-variables-seleccionadas-sin-balanceo" id="toc-caso-3-variables-seleccionadas-sin-balanceo" class="nav-link" data-scroll-target="#caso-3-variables-seleccionadas-sin-balanceo">Caso 3: Variables Seleccionadas / Sin Balanceo</a></li>
  <li><a href="#caso-4-variables-seleccionadas-con-balanceo" id="toc-caso-4-variables-seleccionadas-con-balanceo" class="nav-link" data-scroll-target="#caso-4-variables-seleccionadas-con-balanceo">Caso 4: Variables Seleccionadas / Con Balanceo</a></li>
  </ul></li>
  <li><a href="#análisis-comparativo-del-desempeño-de-los-modelos" id="toc-análisis-comparativo-del-desempeño-de-los-modelos" class="nav-link" data-scroll-target="#análisis-comparativo-del-desempeño-de-los-modelos">4.Análisis comparativo del desempeño de los modelos</a>
  <ul class="collapse">
  <li><a href="#resultados-de-los-modelos" id="toc-resultados-de-los-modelos" class="nav-link" data-scroll-target="#resultados-de-los-modelos">Resultados de los modelos</a></li>
  <li><a href="#ranking-de-los-mejores-modelos" id="toc-ranking-de-los-mejores-modelos" class="nav-link" data-scroll-target="#ranking-de-los-mejores-modelos">Ranking de los mejores modelos</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#hallazgos-y-conclusion-del-proyecto" id="toc-hallazgos-y-conclusion-del-proyecto" class="nav-link" data-scroll-target="#hallazgos-y-conclusion-del-proyecto">Hallazgos y conclusion del proyecto</a>
  <ul class="collapse">
  <li><a href="#hallazgos" id="toc-hallazgos" class="nav-link" data-scroll-target="#hallazgos">Hallazgos</a>
  <ul class="collapse">
  <li><a href="#variables-influyentes-en-el-éxito-o-fracaso-académico-en-matemática" id="toc-variables-influyentes-en-el-éxito-o-fracaso-académico-en-matemática" class="nav-link" data-scroll-target="#variables-influyentes-en-el-éxito-o-fracaso-académico-en-matemática">Variables influyentes en el Éxito o Fracaso académico en matemática</a></li>
  <li><a href="#resumen-de-los-modelos-más-eficaces" id="toc-resumen-de-los-modelos-más-eficaces" class="nav-link" data-scroll-target="#resumen-de-los-modelos-más-eficaces">Resumen de los Modelos Más Eficaces</a></li>
  </ul></li>
  <li><a href="#conclusión" id="toc-conclusión" class="nav-link" data-scroll-target="#conclusión">Conclusión</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análisis Predictivo de Rendimiento Estudiantil</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Equipo 1: Víctor Ochoa y Salvador Rodríguez </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introducción" class="level1">
<h1>Introducción</h1>
<p>El conjunto de datos <a href="https://doi.org/10.24432/C5TG7T"><em>Student Performance</em></a> contiene información detallada sobre el rendimiento académico de estudiantes de secundaria en la asignatura de Matemáticas, junto con una amplia gama de variables demográficas, sociales, familiares y conductuales. Los datos fueron recopilados mediante encuestas en dos escuelas secundarias públicas de Portugal y están disponibles en el repositorio UCI Machine Learning.</p>
<p>Basados en la descripción del respositorio, el rendimiento académico de los estudiantes no depende únicamente de su capacidad cognitiva, sino que está fuertemente influenciado por factores contextuales como el entorno familiar, los hábitos de estudio, el apoyo escolar, las relaciones sociales y las condiciones socioeconómicas. En este contexto, identificar tempranamente a los estudiantes en riesgo de reprobación permite a las instituciones educativas implementar estrategias de intervención oportuna, optimizando recursos y promoviendo la equidad en el aprendizaje. Por ello, es crucial desarrollar modelos predictivos que, a partir de variables observables al inicio del curso, puedan anticipar el resultado académico final.</p>
<p>El conjunto de datos incluye 395 observaciones y 33 variables, entre las que se encuentran:</p>
<ul>
<li><p><strong>Demográficas</strong>: edad, género, tipo de residencia (urbana o rural).</p></li>
<li><p><strong>Familiares</strong>: nivel educativo de los padres, ocupación, tipo de tutor, calidad de las relaciones familiares.</p></li>
<li><p><strong>Académicas</strong>: número de ausencias, fracasos previos, apoyo escolar extra, acceso a internet.</p></li>
<li><p><strong>De comportamiento</strong>: tiempo de estudio, frecuencia de salidas con amigos, consumo de alcohol, tiempo libre.</p></li>
<li><p><strong>De desempeño</strong>: calificaciones en el primer (G1), segundo (G2) y tercer período (G3).</p></li>
</ul>
<p>En este proyecto de <strong>clasificación binaria</strong>; el objetivo es detectar si un estudiante aprobará o reprobará, transformando la variable objetivo continua (G3) en una variable categórica binaria. Así, en lugar de predecir la calificación exacta, se define la variable respuesta <strong>Pass</strong> como:</p>
<p><span class="math display">\[ \texttt{Pass} =\begin{cases}\text{yes}, &amp; \text{si } \texttt{G3} \geq 10 \\\text{no}, &amp; \text{si } \texttt{G3} &lt; 10\end{cases} \]</span></p>
<p>Este umbral (10 sobre 20) corresponde al criterio tradicional de aprobación en el sistema educativo portugués . Es importante destacar que, para preservar la validez de la predicción temprana, las calificaciones intermedias (G1 y G2) se excluyen del conjunto de predictores, evitando así cualquier fuga de información y asegurando que el modelo se base únicamente en factores observables antes del cierre del curso.</p>
</section>
<section id="business-understanding" class="level1">
<h1>Business understanding</h1>
<p>Planteamos algunas preguntas sobre nuestros datos:</p>
<ul>
<li>¿Un mayor nivel educativo de los padres se asocia con una mayor probabilidad de aprobación?</li>
<li>¿El número de fracasos previos es el predictor más fuerte de reprobación?</li>
<li>¿El apoyo escolar extra mejora significativamente las probabilidades de aprobación?</li>
<li>¿Una mayor frecuencia de salidas con amigos se asocia con menor rendimiento?</li>
</ul>
</section>
<section id="data-understanding" class="level1">
<h1>Data understanding</h1>
<section id="descripción-del-conjunto-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="descripción-del-conjunto-de-datos">Descripción del Conjunto de Datos</h2>
<p>El proyecto utiliza el conjunto de datos de Rendimiento Estudiantil que contiene 395 estudiantes con 33 atributos que describen variable de tipo: demografía, contexto social y registros académicos.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Variables Demográficas</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 71%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Tipo</th>
<th style="text-align: left;">Valores</th>
<th style="text-align: left;">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">school</td>
<td style="text-align: left;">Categórica</td>
<td style="text-align: left;">GP, MS</td>
<td style="text-align: left;">Escuela del estudiante (GP: Gabriel Pereira, MS: Mousinho da Silveira)</td>
</tr>
<tr class="even">
<td style="text-align: left;">sex</td>
<td style="text-align: left;">Categórica</td>
<td style="text-align: left;">F, M</td>
<td style="text-align: left;">Sexo del estudiante (F: Femenino, M: Masculino)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: left;">Numérica</td>
<td style="text-align: left;">15-22</td>
<td style="text-align: left;">Edad del estudiante en años</td>
</tr>
<tr class="even">
<td style="text-align: left;">address</td>
<td style="text-align: left;">Categórica</td>
<td style="text-align: left;">U, R</td>
<td style="text-align: left;">Tipo de domicilio del estudiante (U: Urbano, R: Rural)</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Variables Escolares</caption>
<colgroup>
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 24%">
<col style="width: 58%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Tipo</th>
<th style="text-align: left;">Valores</th>
<th style="text-align: left;">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">reason</td>
<td style="text-align: left;">Categórica</td>
<td style="text-align: left;">home, reputation, course, other</td>
<td style="text-align: left;">Razón para elegir esta escuela</td>
</tr>
<tr class="even">
<td style="text-align: left;">traveltime</td>
<td style="text-align: left;">Ordinal</td>
<td style="text-align: left;">1-4</td>
<td style="text-align: left;">Tiempo de viaje casa-escuela (1: &lt;15min, 2: 15-30min, 3: 30min-1h, 4: &gt;1h)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">studytime</td>
<td style="text-align: left;">Ordinal</td>
<td style="text-align: left;">1-4</td>
<td style="text-align: left;">Tiempo de estudio semanal (1: &lt;2h, 2: 2-5h, 3: 5-10h, 4: &gt;10h)</td>
</tr>
<tr class="even">
<td style="text-align: left;">failures</td>
<td style="text-align: left;">Numérica</td>
<td style="text-align: left;">0-4</td>
<td style="text-align: left;">Número de fallos académicos previos</td>
</tr>
<tr class="odd">
<td style="text-align: left;">schoolsup</td>
<td style="text-align: left;">Categórica</td>
<td style="text-align: left;">yes, no</td>
<td style="text-align: left;">Recibe apoyo educativo extra de la escuela</td>
</tr>
<tr class="even">
<td style="text-align: left;">famsup</td>
<td style="text-align: left;">Categórica</td>
<td style="text-align: left;">yes, no</td>
<td style="text-align: left;">Recibe apoyo educativo de la familia</td>
</tr>
<tr class="odd">
<td style="text-align: left;">paid</td>
<td style="text-align: left;">Categórica</td>
<td style="text-align: left;">yes, no</td>
<td style="text-align: left;">Toma clases extra pagadas en matemáticas</td>
</tr>
<tr class="even">
<td style="text-align: left;">activities</td>
<td style="text-align: left;">Categórica</td>
<td style="text-align: left;">yes, no</td>
<td style="text-align: left;">Participa en actividades extracurriculares</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nursery</td>
<td style="text-align: left;">Categórica</td>
<td style="text-align: left;">yes, no</td>
<td style="text-align: left;">Asistió a guardería</td>
</tr>
<tr class="even">
<td style="text-align: left;">higher</td>
<td style="text-align: left;">Categórica</td>
<td style="text-align: left;">yes, no</td>
<td style="text-align: left;">Desea seguir educación superior</td>
</tr>
<tr class="odd">
<td style="text-align: left;">absences</td>
<td style="text-align: left;">Numérica</td>
<td style="text-align: left;">0-93</td>
<td style="text-align: left;">Número de ausencias escolares</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Variables Sociales y de Salud</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Tipo</th>
<th style="text-align: left;">Valores</th>
<th style="text-align: left;">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">internet</td>
<td style="text-align: left;">Categórica</td>
<td style="text-align: left;">yes, no</td>
<td style="text-align: left;">Tiene acceso a internet en casa</td>
</tr>
<tr class="even">
<td style="text-align: left;">romantic</td>
<td style="text-align: left;">Categórica</td>
<td style="text-align: left;">yes, no</td>
<td style="text-align: left;">Está en una relación romántica</td>
</tr>
<tr class="odd">
<td style="text-align: left;">famrel</td>
<td style="text-align: left;">Ordinal</td>
<td style="text-align: left;">1-5</td>
<td style="text-align: left;">Calidad de relaciones familiares (1: muy mala - 5: excelente)</td>
</tr>
<tr class="even">
<td style="text-align: left;">freetime</td>
<td style="text-align: left;">Ordinal</td>
<td style="text-align: left;">1-5</td>
<td style="text-align: left;">Tiempo libre después de la escuela (1: muy bajo - 5: muy alto)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">goout</td>
<td style="text-align: left;">Ordinal</td>
<td style="text-align: left;">1-5</td>
<td style="text-align: left;">Frecuencia de salidas con amigos (1: muy baja - 5: muy alta)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dalc</td>
<td style="text-align: left;">Ordinal</td>
<td style="text-align: left;">1-5</td>
<td style="text-align: left;">Consumo de alcohol entre semana (1: muy bajo - 5: muy alto)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Walc</td>
<td style="text-align: left;">Ordinal</td>
<td style="text-align: left;">1-5</td>
<td style="text-align: left;">Consumo de alcohol en fin de semana (1: muy bajo - 5: muy alto)</td>
</tr>
<tr class="even">
<td style="text-align: left;">health</td>
<td style="text-align: left;">Ordinal</td>
<td style="text-align: left;">1-5</td>
<td style="text-align: left;">Estado de salud actual (1: muy malo - 5: muy bueno)</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Primeras 10 observaciones del dataset</caption>
<colgroup>
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">school</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">age</th>
<th style="text-align: left;">address</th>
<th style="text-align: left;">famsize</th>
<th style="text-align: left;">pstatus</th>
<th style="text-align: right;">medu</th>
<th style="text-align: right;">fedu</th>
<th style="text-align: left;">mjob</th>
<th style="text-align: left;">fjob</th>
<th style="text-align: left;">reason</th>
<th style="text-align: left;">guardian</th>
<th style="text-align: right;">traveltime</th>
<th style="text-align: right;">studytime</th>
<th style="text-align: right;">failures</th>
<th style="text-align: left;">schoolsup</th>
<th style="text-align: left;">famsup</th>
<th style="text-align: left;">paid</th>
<th style="text-align: left;">activities</th>
<th style="text-align: left;">nursery</th>
<th style="text-align: left;">higher</th>
<th style="text-align: left;">internet</th>
<th style="text-align: left;">romantic</th>
<th style="text-align: right;">famrel</th>
<th style="text-align: right;">freetime</th>
<th style="text-align: right;">goout</th>
<th style="text-align: right;">dalc</th>
<th style="text-align: right;">walc</th>
<th style="text-align: right;">health</th>
<th style="text-align: right;">absences</th>
<th style="text-align: right;">g1</th>
<th style="text-align: right;">g2</th>
<th style="text-align: right;">g3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GP</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;">U</td>
<td style="text-align: left;">GT3</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">at_home</td>
<td style="text-align: left;">teacher</td>
<td style="text-align: left;">course</td>
<td style="text-align: left;">mother</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">GP</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">17</td>
<td style="text-align: left;">U</td>
<td style="text-align: left;">GT3</td>
<td style="text-align: left;">T</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">at_home</td>
<td style="text-align: left;">other</td>
<td style="text-align: left;">course</td>
<td style="text-align: left;">father</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GP</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">U</td>
<td style="text-align: left;">LE3</td>
<td style="text-align: left;">T</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">at_home</td>
<td style="text-align: left;">other</td>
<td style="text-align: left;">other</td>
<td style="text-align: left;">mother</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">GP</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">U</td>
<td style="text-align: left;">GT3</td>
<td style="text-align: left;">T</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">health</td>
<td style="text-align: left;">services</td>
<td style="text-align: left;">home</td>
<td style="text-align: left;">mother</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GP</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">U</td>
<td style="text-align: left;">GT3</td>
<td style="text-align: left;">T</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">other</td>
<td style="text-align: left;">other</td>
<td style="text-align: left;">home</td>
<td style="text-align: left;">father</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">GP</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">U</td>
<td style="text-align: left;">LE3</td>
<td style="text-align: left;">T</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">services</td>
<td style="text-align: left;">other</td>
<td style="text-align: left;">reputation</td>
<td style="text-align: left;">mother</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GP</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">U</td>
<td style="text-align: left;">LE3</td>
<td style="text-align: left;">T</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">other</td>
<td style="text-align: left;">other</td>
<td style="text-align: left;">home</td>
<td style="text-align: left;">mother</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">GP</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">17</td>
<td style="text-align: left;">U</td>
<td style="text-align: left;">GT3</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">other</td>
<td style="text-align: left;">teacher</td>
<td style="text-align: left;">home</td>
<td style="text-align: left;">mother</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GP</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">U</td>
<td style="text-align: left;">LE3</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">services</td>
<td style="text-align: left;">other</td>
<td style="text-align: left;">home</td>
<td style="text-align: left;">mother</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="even">
<td style="text-align: left;">GP</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">U</td>
<td style="text-align: left;">GT3</td>
<td style="text-align: left;">T</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">other</td>
<td style="text-align: left;">other</td>
<td style="text-align: left;">home</td>
<td style="text-align: left;">mother</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">no</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">15</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">Piped data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">395</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">33</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">school</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">sex</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">address</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">famsize</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pstatus</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">mjob</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fjob</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">reason</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">guardian</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">schoolsup</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">famsup</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">paid</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">activities</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">nursery</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">higher</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">internet</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">romantic</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">16.70</td>
<td style="text-align: right;">1.28</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;">▇▅▅▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">medu</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.75</td>
<td style="text-align: right;">1.09</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">▁▃▆▆▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fedu</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.52</td>
<td style="text-align: right;">1.09</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">▁▆▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">traveltime</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">▇▃▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">studytime</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.04</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">▅▇▁▂▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">failures</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">famrel</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.94</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▁▁▃▇▅</td>
</tr>
<tr class="even">
<td style="text-align: left;">freetime</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.24</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▁▃▇▆▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">goout</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.11</td>
<td style="text-align: right;">1.11</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▂▆▇▅▃</td>
</tr>
<tr class="even">
<td style="text-align: left;">dalc</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.48</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">walc</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.29</td>
<td style="text-align: right;">1.29</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▇▅▅▃▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">health</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.55</td>
<td style="text-align: right;">1.39</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">▂▂▅▃▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">absences</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.71</td>
<td style="text-align: right;">8.00</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">75</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">g1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10.91</td>
<td style="text-align: right;">3.32</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">▂▇▇▆▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">g2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10.71</td>
<td style="text-align: right;">3.76</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">19</td>
<td style="text-align: left;">▁▂▇▆▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">g3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10.42</td>
<td style="text-align: right;">4.58</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">▂▃▇▅▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Este conjunto de datos contiene información sobre 395 estudiantes, sin valores faltantes. Incluye 33 variables que describen aspectos personales, familiares, sociales y académicos. Hay 17 variables categóricas, como el género, la escuela o el motivo para elegir esta, y 16 numéricas, como edad, tiempo de estudio, número de ausencias y calificaciones en los tres periodos (g1, g2, g3). Todos los datos están completos, lo que permite un análisis confiable del rendimiento académico y los factores asociados.</p>
</section>
</section>
<section id="análisis-exploratorio-de-datos-eda" class="level1">
<h1>Análisis Exploratorio de Datos (EDA)</h1>
<section id="varibale-g3-sin-ser-binaria" class="level2">
<h2 class="anchored" data-anchor-id="varibale-g3-sin-ser-binaria">Varibale <span class="math inline">\(G3\)</span> sin ser binaria</h2>
<section id="análisis-univariado-de-la-variable-objetivo-textg3" class="level3">
<h3 class="anchored" data-anchor-id="análisis-univariado-de-la-variable-objetivo-textg3">Análisis Univariado de la Variable Objetivo (<span class="math inline">\(\text{G3}\)</span>)</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ReporteProyect_VF_files/figure-html/g3-distribution-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
### Estadísticas Descriptivas de G3</code></pre>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Estadísticas clave de la Nota Final (G3).</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mediana</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">10.43</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">20</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La distribución de la nota final ($\text{G3}$) presenta un sesgo negativo (hacia la izquierda), ya que la Mediana (11) es ligeramente superior a la Media (10.42), aunque ambos valores son cercanos. El rango completo de notas es utilizado, yendo de $\text{0}$ (nota mínima) a $\text{20}$ (nota máxima). La presencia de una alta frecuencia de notas cero sugiere un número significativo de reprobados o no presentados.</p>
</section>
<section id="análisis-bivariado-factores-numéricos-vs.-textg3" class="level3">
<h3 class="anchored" data-anchor-id="análisis-bivariado-factores-numéricos-vs.-textg3">Análisis Bivariado: Factores Numéricos vs.&nbsp;<span class="math inline">\(\text{G3}\)</span></h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ReporteProyect_VF_files/figure-html/correlation-matrix-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Las correlaciones más fuertes y negativas se encuentran con <strong><code>failures</code></strong> (-0.37) y <strong><code>age</code></strong> (-0.23). Los estudiantes con más fallas previas y de mayor edad tienden a tener notas <span class="math inline">\(\text{G3}\)</span> más bajas.</p></li>
<li><p>Existe una correlación positiva con la <strong><code>medu</code></strong> (Educación de la Madre, 0.22) y <strong><code>fedu</code></strong> (Educación del Padre, 0.17).</p></li>
</ul>
</section>
<section id="relaciones-gráficas-de-factores-clave-vs.-textg3" class="level3">
<h3 class="anchored" data-anchor-id="relaciones-gráficas-de-factores-clave-vs.-textg3">Relaciones Gráficas de Factores Clave vs.&nbsp;<span class="math inline">\(\text{G3}\)</span></h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ReporteProyect_VF_files/figure-html/key-numerical-vs-g3-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>Fallas Previas (<code>failures</code>):</strong> Existe una <strong>relación negativa muy fuerte</strong>. A medida que el número de fallas previas aumenta (de 0 a <span class="math inline">\(&gt;3\)</span>), la <strong>mediana de</strong> <span class="math inline">\(\text{G3}\)</span> cae drásticamente, validando que el historial académico es un predictor que puede ser muy útil.</li>
</ul>
<!-- -->
<ul>
<li><p><strong>Tiempo de Estudio (<code>studytime</code>):</strong> La relación es <strong>positiva</strong>. Los estudiantes que dedican más tiempo a estudiar semanalmente (niveles 2, 3 y 4) muestran consistentemente una <strong>mediana de</strong> <span class="math inline">\(\text{G3}\)</span> superior a aquellos que estudian menos de 2 horas (nivel 1).</p></li>
<li><p><strong>Ausencias (<code>absences</code>):</strong> El gráfico de dispersión muestra una <strong>correlación muy débil</strong> con <span class="math inline">\(\text{G3}\)</span>, ya que la línea de tendencia es casi plana, lo que sugiere que el número de ausencias por sí solo no es un predictor lineal fuerte de la nota final para la mayoría de los estudiantes.</p></li>
</ul>
</section>
<section id="análisis-bivariado-factores-categóricos-vs.-textg3" class="level3">
<h3 class="anchored" data-anchor-id="análisis-bivariado-factores-categóricos-vs.-textg3">Análisis Bivariado: Factores Categóricos vs.&nbsp;<span class="math inline">\(\text{G3}\)</span></h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ReporteProyect_VF_files/figure-html/key-categorical-vs-g3-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>Deseo de Educación Superior (<code>higher</code>):</strong> Esta es la variable categórica <strong>más influyente</strong>. Los estudiantes que expresan un deseo de seguir estudios superiores (<strong>“yes”</strong>) tienen una <strong>mediana de</strong> <span class="math inline">\(\text{G3}\)</span> significativamente más alta (alrededor de 12) que aquellos que no lo desean, lo que puede indicar la importancia de la <strong>motivación</strong> como predictor.</li>
</ul>
<!-- -->
<ul>
<li><p><strong>Sexo (<code>sex</code>):</strong> Existe una <strong>diferencia sutil pero verificable</strong> en el rendimiento. Los estudiantes varones (<strong>M</strong>) registran una <strong>mediana de</strong> <span class="math inline">\(\text{G3}\)</span> superior (11.00) a la de las estudiantes mujeres (<strong>F</strong>, 10.00).</p></li>
<li><p><strong>Apoyo Familiar (<code>famsup</code>):</strong> El impacto de contar con apoyo familiar es <strong>mínimo</strong>. La diferencia en la mediana de <span class="math inline">\(\text{G3}\)</span> entre los grupos es <strong>casi nula</strong>, lo que indica que es probable que esta variable sea un predictor débil para el modelado.</p></li>
</ul>
</section>
<section id="respuesta-preliminar-a-las-preguntas-de-business-understanding" class="level3">
<h3 class="anchored" data-anchor-id="respuesta-preliminar-a-las-preguntas-de-business-understanding">Respuesta preliminar a las preguntas de Business understanding</h3>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Resumen de las Conclusiones Preliminares del EDA frente a las Preguntas de Negocio</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Pregunta de Negocio</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Variables Clave</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Análisis del EDA</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Conclusión Preliminar</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; color: black !important; background-color: rgba(230, 243, 255, 255) !important;">¿Un mayor nivel educativo de los padres se asocia con una mayor probabilidad de aprobación?</td>
<td style="text-align: left; color: black !important; background-color: rgba(230, 243, 255, 255) !important;">G3 vs. Medu y Fedu</td>
<td style="text-align: left; color: black !important; background-color: rgba(230, 243, 255, 255) !important;">Correlación positiva y moderada con G3 (Medu: 0.22, Fedu: 0.17).</td>
<td style="text-align: left; color: black !important; background-color: rgba(230, 243, 255, 255) !important;">Sí. Hay una asociación positiva. El nivel educativo de los padres se correlaciona con un mayor rendimiento.</td>
</tr>
<tr class="even">
<td style="text-align: left; color: black !important; background-color: rgba(255, 230, 230, 255) !important;">¿El número de fracasos previos es el predictor más fuerte de reprobación?</td>
<td style="text-align: left; color: black !important; background-color: rgba(255, 230, 230, 255) !important;">G3 vs. failures</td>
<td style="text-align: left; color: black !important; background-color: rgba(255, 230, 230, 255) !important;">Correlación más fuerte y negativa de todos los factores (-0.37). Caída drástica de la mediana de G3.</td>
<td style="text-align: left; color: black !important; background-color: rgba(255, 230, 230, 255) !important;">Sí. failures es el predictor de bajo rendimiento más potente entre los factores asociados.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">¿El apoyo escolar extra mejora significativamente las probabilidades de aprobación?</td>
<td style="text-align: left;">G3 vs. schoolsup</td>
<td style="text-align: left;">Mediana de G3 para estudiantes con apoyo (9.0) es inferior a la de sin apoyo (11.0).</td>
<td style="text-align: left;">Inconcluso. schoolsup es un indicador de riesgo, lo que sugiere que identifica a estudiantes con bajo rendimiento inicial.</td>
</tr>
<tr class="even">
<td style="text-align: left;">¿Una mayor frecuencia de salidas con amigos se asocia con menor rendimiento?</td>
<td style="text-align: left;">G3 vs. goout</td>
<td style="text-align: left;">Correlación negativa, pero débil (-0.13). Tendencia a la baja en G3 con más salidas.</td>
<td style="text-align: left;">Sí, existe una asociación negativa, pero su impacto es menor que otros factores, como failures o higher.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
</section>
<section id="analisis-eda-para-varibale-g3-binaria." class="level2">
<h2 class="anchored" data-anchor-id="analisis-eda-para-varibale-g3-binaria.">Analisis EDA para varibale <span class="math inline">\(G3\)</span> binaria.</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ReporteProyect_VF_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El deseo de estudiar educación superior es el predictor más fuerte. Los estudiantes que responden <strong>‘yes’</strong> presentan una tasa de aprobación notablemente superior, exactamente del <strong>65%</strong>, mientras que aquellos que responden <strong>‘no’</strong> tienen una tasa de aprobación de apenas <strong>2%</strong>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ReporteProyect_VF_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Existe una relación inversa crítica. Los estudiantes sin fracasos previos (<strong>0</strong>) tienen una tasa de aprobación de casi <strong>60%</strong>. La tasa cae drásticamente a menos del <strong>6%</strong> para aquellos con solo <strong>un</strong> fracaso previo, y la aprobación es casi nula para 2 o más fracasos. El impacto de los <strong><code>failures</code></strong> es importante.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>train_final_bin <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> absences, <span class="at">fill =</span> Status)) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución de Ausencias según Estado de Aprobación"</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Número de Ausencias"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_legend</span>(<span class="at">title =</span> <span class="st">"Estado"</span>)) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ReporteProyect_VF_files/figure-html/train-density-absences-approval-v2-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>La curva de densidad para los estudiantes <strong>‘Reprobado’</strong> está ligeramente desplazada a la <strong>derecha</strong>, lo que indica que tienen un número de ausencias marginalmente mayor que los <strong>‘Aprobado’</strong>. Ambas curvas se superponen fuertemente, sugiriendo que las <strong><code>absences</code></strong> no son un predictor tan fuerte para la clasificación como los factores categóricos.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir el target binario a numérico (0/1)</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>train_corr <span class="ot">&lt;-</span> train_final_bin <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Status_num =</span> <span class="fu">as.numeric</span>(Status <span class="sc">==</span> <span class="st">"Aprobado"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Status_num, age, traveltime, studytime, failures, </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>         famrel, freetime, goout, Dalc, Walc, health, absences,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>         Medu, Fedu) <span class="co"># Incluyendo Medu/Fedu que son ordinales</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la correlación de Pearson</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>corr_results <span class="ot">&lt;-</span> <span class="fu">cor</span>(train_corr, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Extraer solo la fila de correlación con Status_num y ordenar</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>corr_status <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">colnames</span>(corr_results),</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">Correlacion =</span> corr_results[<span class="st">"Status_num"</span>, ]</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Variable <span class="sc">!=</span> <span class="st">"Status_num"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Correlacion)))</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>corr_status <span class="sc">%&gt;%</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>) <span class="sc">%&gt;%</span> <span class="co"># Mostrar los 10 predictores más fuertes</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Top 10 Predictores Numéricos/Ordinales asociados a Status"</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 10 Predictores Numéricos/Ordinales asociados a Status</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Correlacion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">failures</td>
<td style="text-align: right;">-0.330</td>
</tr>
<tr class="even">
<td style="text-align: left;">age</td>
<td style="text-align: right;">-0.198</td>
</tr>
<tr class="odd">
<td style="text-align: left;">goout</td>
<td style="text-align: right;">-0.165</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fedu</td>
<td style="text-align: right;">0.144</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Medu</td>
<td style="text-align: right;">0.131</td>
</tr>
<tr class="even">
<td style="text-align: left;">famrel</td>
<td style="text-align: right;">0.085</td>
</tr>
<tr class="odd">
<td style="text-align: left;">studytime</td>
<td style="text-align: right;">0.084</td>
</tr>
<tr class="even">
<td style="text-align: left;">absences</td>
<td style="text-align: right;">-0.066</td>
</tr>
<tr class="odd">
<td style="text-align: left;">health</td>
<td style="text-align: right;">-0.033</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dalc</td>
<td style="text-align: right;">-0.029</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Los <strong>10 principales predictores</strong> numéricos/ordinales de <strong>StatusVariable</strong> muestran que la variable <strong>failures</strong> (fracasos) tiene la correlación negativa más fuerte <span class="math inline">\((-0.351)\)</span>, lo que sugiere que <strong>menos fracasos</strong> se asocian con un mejor estatus. Otros factores con correlación negativa incluyen <strong>age</strong> <span class="math inline">\((-0.195)\)</span>, <strong>goout</strong> <span class="math inline">\((-0.179)\)</span>, <strong>Dalc</strong> (consumo de alcohol diario, <span class="math inline">\(-0.097\)</span>), <strong>absences</strong> <span class="math inline">\((-0.095)\)</span>, <strong>traveltime</strong> <span class="math inline">\((-0.077)\)</span> y <strong>health</strong> <span class="math inline">\((-0.074)\)</span>. Por otro lado, la <strong>educación de la madre (<code>Medu</code>,</strong> <span class="math inline">\(0.174\)</span>) y la <strong>educación del padre (<code>Fedu</code>,</strong> <span class="math inline">\(0.131\)</span>) tienen correlaciones positivas, indicando que <strong>mayor nivel educativo de los padres</strong> se relaciona con un mejor estatus. Finalmente, <strong>studytime</strong> <span class="math inline">\((0.107)\)</span> también muestra una correlación positiva.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcd)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Seleccionar todas las variables categóricas que quedan en el dataset</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>categorical_vars <span class="ot">&lt;-</span> <span class="fu">names</span>(train_final_bin)[<span class="fu">sapply</span>(train_final_bin, is.factor) <span class="sc">|</span> <span class="fu">sapply</span>(train_final_bin, is.character)]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Lista para almacenar los resultados</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>cramer_v_results <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (var <span class="cf">in</span> categorical_vars) {</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (var <span class="sc">!=</span> <span class="st">"Status"</span>) {</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    tabla_contingencia <span class="ot">&lt;-</span> <span class="fu">table</span>(train_final_bin<span class="sc">$</span>Status, train_final_bin[[var]])</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calcular Chi-cuadrado y V de Cramer</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    test_results <span class="ot">&lt;-</span> <span class="fu">assocstats</span>(tabla_contingencia)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    cramer_v_results[[var]] <span class="ot">&lt;-</span> test_results<span class="sc">$</span>cramer</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir resultados a dataframe y ordenar</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>cramer_v_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">names</span>(cramer_v_results),</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">Cramer_V =</span> <span class="fu">unlist</span>(cramer_v_results)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Cramer_V))</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"### Fuerza de Asociación (V de Cramer) con Status</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>### Fuerza de Asociación (V de Cramer) con Status</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cramer_v_df <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Top 10 Predictores Categóricos/Nominales asociados a Status"</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 10 Predictores Categóricos/Nominales asociados a Status</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Cramer_V</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">higher</td>
<td style="text-align: left;">higher</td>
<td style="text-align: right;">0.165</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mjob</td>
<td style="text-align: left;">Mjob</td>
<td style="text-align: right;">0.113</td>
</tr>
<tr class="odd">
<td style="text-align: left;">guardian</td>
<td style="text-align: left;">guardian</td>
<td style="text-align: right;">0.109</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fjob</td>
<td style="text-align: left;">Fjob</td>
<td style="text-align: right;">0.099</td>
</tr>
<tr class="odd">
<td style="text-align: left;">paid</td>
<td style="text-align: left;">paid</td>
<td style="text-align: right;">0.089</td>
</tr>
<tr class="even">
<td style="text-align: left;">schoolsup</td>
<td style="text-align: left;">schoolsup</td>
<td style="text-align: right;">0.088</td>
</tr>
<tr class="odd">
<td style="text-align: left;">reason</td>
<td style="text-align: left;">reason</td>
<td style="text-align: right;">0.083</td>
</tr>
<tr class="even">
<td style="text-align: left;">famsize</td>
<td style="text-align: left;">famsize</td>
<td style="text-align: right;">0.080</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pstatus</td>
<td style="text-align: left;">Pstatus</td>
<td style="text-align: right;">0.079</td>
</tr>
<tr class="even">
<td style="text-align: left;">famsup</td>
<td style="text-align: left;">famsup</td>
<td style="text-align: right;">0.073</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Los <strong>10 principales predictores categóricos</strong> de <strong>StatusVariable</strong> se evaluaron usando <span class="math inline">\(V\)</span> de Cramer. La <strong>ocupación de la madre</strong> (<code>Mjob</code>, <span class="math inline">\(0.162\)</span>), la <strong>ocupación del padre</strong> (<code>Fjob</code>, <span class="math inline">\(0.152\)</span>) y el <strong>tutor</strong> (<code>guardian</code>, <span class="math inline">\(0.152\)</span>) son los más fuertemente asociados. Otros predictores importantes incluyen la intención de tomar <strong>estudios superiores</strong> (<code>higher</code>, <span class="math inline">\(0.148\)</span>), si la persona <strong>paga clases extra</strong> (<code>paid</code>, <span class="math inline">\(0.118\)</span>), la <strong>razón</strong> para elegir la escuela (<code>reason</code>, <span class="math inline">\(0.115\)</span>) y la existencia de una relación <strong>romántica</strong> (<code>romantic</code>, <span class="math inline">\(0.106\)</span>). Además, tener acceso a <strong>internet</strong> (<code>internet</code>, <span class="math inline">\(0.103\)</span>), el <strong>apoyo escolar</strong> (<code>schoolsup</code>, <span class="math inline">\(0.099\)</span>) y el <strong>tamaño familiar</strong> (<code>famsize</code>, <span class="math inline">\(0.075\)</span>) también muestran asociaciones relevantes con la variable de estatus.</p>
</section>
</section>
<section id="modelado-y-evaluacion." class="level1">
<h1>Modelado y evaluacion.</h1>
<section id="preparación-de-la-base-de-datos-para-el-modelaje." class="level2">
<h2 class="anchored" data-anchor-id="preparación-de-la-base-de-datos-para-el-modelaje.">1. Preparación de la base de datos para el modelaje.</h2>
<p>Primero, se cargan las librerías necesarias y la base de datos. Luego se realiza una conversión de variables numéricas y se define a la variable objetivo <code>Status</code> basada en la nota final (G3).</p>
<p><strong>Análisis de la Distribución de Clases:</strong> Al observar la estructura de los datos, se observó un pequeño desbalance de clases. Según los registros se tiene <strong>130 casos de “Fail”</strong> y <strong>265 casos de “Pass”</strong>. En términos proporcionales, esto representa aproximadamente un <strong>32.9% de reprobados</strong> frente a un <strong>67.1% de aprobados</strong>. Este pequeño desequilibrio sugiere que los modelos sin balanceo podrían tener dificultades para detectar la clase minoritaria (“Fail”).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Conteos:"

Fail Pass 
 130  265 
[1] "Proporciones:"

     Fail      Pass 
0.3291139 0.6708861 </code></pre>
</div>
</div>
</section>
<section id="selección-de-variables-relevantes-para-el-status-de-un-estudiante" class="level2">
<h2 class="anchored" data-anchor-id="selección-de-variables-relevantes-para-el-status-de-un-estudiante">2. Selección de Variables Relevantes para el Status de un Estudiante</h2>
<p>El conjunto de datos original contiene numerosas variables, pero posiblemente no todas contribuyan a la detección de un estudiante en riesgo de reprobar. Incluir información irrelevante o redundante introduce “ruido” que puede llevar al sobreajuste (overfitting), haciendo que el modelo memorice los datos de entrenamiento en lugar de aprender patrones reales. Por tanto, filtrar las variables puede resultar ser una buena medida para simplificar la complejidad del modelo y mejorar su capacidad de generalización ante nuevos estudiantes.</p>
<section id="métodos-de-selección" class="level3">
<h3 class="anchored" data-anchor-id="métodos-de-selección">Métodos de selección</h3>
<p>Para lograr este proceso de selección de manera objetiva y evitar el sesgo inherente a un único algoritmo, se aplicó una estrategia de consenso utilizando tres técnicas distintas de selección:</p>
<ol type="a">
<li><p>Chi-Cuadrado: Para evaluar la relevancia estadística entre variables categóricas.</p></li>
<li><p>Boruta: Un método basado en Random Forest diseñado para detectar todas las variables relevantes (incluso las que tienen interacciones complejas).</p></li>
<li><p>RFE (Eliminación Recursiva de Características): Para encontrar el subconjunto óptimo de variables que maximiza la precisión del modelo mediante validación cruzada.</p></li>
</ol>
</section>
<section id="resultados-del-análisis-de-importancia" class="level3">
<h3 class="anchored" data-anchor-id="resultados-del-análisis-de-importancia">Resultados del Análisis de Importancia</h3>
<p>Chi-Cuadrado: Destacó a higher (intención de cursar educación superior) como la variable más significativa, siendo la única validada por los tres métodos (3 votos).</p>
<p>Boruta: Confirmó la importancia crítica de failures (reprobaciones pasadas), schoolsup (apoyo educativo extra) y goout (salidas con amigos).</p>
<p>Discrepancias: Se observó que variables como guardian (tutor) y age (edad) fueron sugeridas por algunos métodos pero rechazadas por otros.</p>
<p>Criterio de Decisión (Matriz de Consenso): Para resolver estas discrepancias, se implementó una Matriz de votación uutomatizada. Se estableción como regla: una variable solo se selecciona si cuenta con el consenso de al menos 2 de los 3 algoritmos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "--- TOP VARIABLES POR P-VALUE (CHI-CUADRADO) ---"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    Variable    P_Value
15    higher 0.00385021
17  romantic 0.06740352
10 schoolsup 0.06799817
9   guardian 0.07000507
12      paid 0.08287639
2        sex 0.19488312
8     reason 0.21284952
6       Mjob 0.25758057
16  internet 0.27812236
11    famsup 0.28594799</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ReporteProyect_VF_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "--- VARIABLES CONFIRMADAS POR BORUTA ---"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            meanImp medianImp     minImp    maxImp  normHits  decision
guardian   5.290222  5.441537  0.4634108 10.562290 0.8282828 Confirmed
failures  26.389386 27.556590 15.9207702 31.717845 1.0000000 Confirmed
schoolsup  7.886669  7.917989  3.0724807 14.502171 0.9595960 Confirmed
higher     4.808679  4.740830  1.8762165  8.538176 0.8181818 Confirmed
goout      6.716674  6.694132  1.3875369 11.579342 0.9393939 Confirmed
absences  10.081463 10.181124  4.4796499 15.196016 0.9898990 Confirmed</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ReporteProyect_VF_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "--- VARIABLES ÓPTIMAS SEGÚN RFE ---"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "failures"  "absences"  "goout"     "schoolsup" "higher"    "age"      
[7] "studytime" "sex"       "famsize"  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "--- TABLA DE CONSENSO (VOTACIÓN) ---"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    Variable Chi_Cuad_Sig Boruta_Conf RFE_Opt Votos
1     higher         TRUE        TRUE    TRUE     3
3   failures        FALSE        TRUE    TRUE     2
4  schoolsup        FALSE        TRUE    TRUE     2
5      goout        FALSE        TRUE    TRUE     2
6   absences        FALSE        TRUE    TRUE     2
2   guardian        FALSE        TRUE   FALSE     1
7        age        FALSE       FALSE    TRUE     1
8  studytime        FALSE       FALSE    TRUE     1
9        sex        FALSE       FALSE    TRUE     1
10   famsize        FALSE       FALSE    TRUE     1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "--- SELECCIÓN AUTOMATIZADA FINAL (Para Casos 3 y 4) ---"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "higher"    "failures"  "schoolsup" "goout"     "absences"  "Status"   </code></pre>
</div>
</div>
<p>Tal como se observa en la tabla de resultados:</p>
<p>Variables como guardian, age, studytime, sex y famsize obtuvieron solo 1 voto, por lo que fueron descartadas para reducir el ruido.</p>
<p>El subconjunto final seleccionado para los modelos optimizados (Casos 3 y 4) consta de las 5 variables que alcanzaron 2 o más votos, más la variable objetivo: higher, failures, schoolsup, goout, absences y Status (Variable Objetivo).</p>
</section>
</section>
<section id="modelado-evaluación-de-4-casos" class="level2">
<h2 class="anchored" data-anchor-id="modelado-evaluación-de-4-casos">3. Modelado: Evaluación de 4 Casos</h2>
<p>Se define una función auxiliar para entrenar y evaluar múltiples modelos (GLM, GBM, RF, SVM, KNN y Rpart) bajo diferentes configuraciones o condiciones.</p>
<section id="caso-1-todas-las-variables-sin-balanceo" class="level3">
<h3 class="anchored" data-anchor-id="caso-1-todas-las-variables-sin-balanceo">Caso 1: Todas las Variables / Sin Balanceo</h3>
<p>En este primer escenario base, se utilizan todas las variables disponibles sin corregir el leve desbalance de clases.</p>
<p>Al ejecutar este caso, se observa que el modelo GBM obtuvo el mejor AUC con 0.6425. Sin embargo, el problema del desbalance es evidente en la métrica de Sensibilidad (capacidad de detectar “Fail”), la cual fue muy baja para la mayoría de los modelos (ej. GBM con 0.25 y Random Forest con 0.4062). Esto indica que los modelos tienden a predecir la clase mayoritaria (“Pass”).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "--- TABLA DE RENDIMIENTO: CASO 1 ---"</code></pre>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resultados: Todas las Variables / Sin Balanceo</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">AUC</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Sensitivity</th>
<th style="text-align: right;">Specificity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">gbm</td>
<td style="text-align: right;">0.6425</td>
<td style="text-align: right;">0.6327</td>
<td style="text-align: right;">0.2500</td>
<td style="text-align: right;">0.8182</td>
</tr>
<tr class="even">
<td style="text-align: left;">glm</td>
<td style="text-align: right;">0.6335</td>
<td style="text-align: right;">0.6122</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.7576</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rf</td>
<td style="text-align: right;">0.6127</td>
<td style="text-align: right;">0.7143</td>
<td style="text-align: right;">0.4062</td>
<td style="text-align: right;">0.8636</td>
</tr>
<tr class="even">
<td style="text-align: left;">rpart</td>
<td style="text-align: right;">0.6125</td>
<td style="text-align: right;">0.6429</td>
<td style="text-align: right;">0.3750</td>
<td style="text-align: right;">0.7727</td>
</tr>
<tr class="odd">
<td style="text-align: left;">svmRadial</td>
<td style="text-align: right;">0.5909</td>
<td style="text-align: right;">0.7041</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.8939</td>
</tr>
<tr class="even">
<td style="text-align: left;">naive_bayes</td>
<td style="text-align: right;">0.5421</td>
<td style="text-align: right;">0.5918</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.7273</td>
</tr>
<tr class="odd">
<td style="text-align: left;">knn</td>
<td style="text-align: right;">0.5386</td>
<td style="text-align: right;">0.6327</td>
<td style="text-align: right;">0.2500</td>
<td style="text-align: right;">0.8182</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="caso-2-todas-las-variables-con-balanceo-up-sampling" class="level3">
<h3 class="anchored" data-anchor-id="caso-2-todas-las-variables-con-balanceo-up-sampling">Caso 2: Todas las Variables / Con Balanceo (Up-Sampling)</h3>
<p>Aquí se aplica la técnica de Up-Sampling para equilibrar las clases durante el entrenamiento.</p>
<p>Análisis de Resultados: Con el balanceo, el modelo GLM lideró la tabla con un AUC de 0.6316. Lo más destacable es la mejora drástica en la Sensibilidad: el GLM subió a 0.50 y el KNN a 0.5312. Aunque la Exactitud (Accuracy) general cae ligeramente respecto al Caso 1, el modelo es mucho más útil para identificar a los estudiantes en riesgo.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "--- TABLA DE RENDIMIENTO: CASO 2 ---"</code></pre>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resultados: Todas las Variables / Con Balanceo (Up-Sampling)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">AUC</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Sensitivity</th>
<th style="text-align: right;">Specificity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">glm</td>
<td style="text-align: right;">0.6316</td>
<td style="text-align: right;">0.6122</td>
<td style="text-align: right;">0.5000</td>
<td style="text-align: right;">0.6667</td>
</tr>
<tr class="even">
<td style="text-align: left;">gbm</td>
<td style="text-align: right;">0.6259</td>
<td style="text-align: right;">0.6327</td>
<td style="text-align: right;">0.4062</td>
<td style="text-align: right;">0.7424</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rf</td>
<td style="text-align: right;">0.6120</td>
<td style="text-align: right;">0.6633</td>
<td style="text-align: right;">0.4062</td>
<td style="text-align: right;">0.7879</td>
</tr>
<tr class="even">
<td style="text-align: left;">svmRadial</td>
<td style="text-align: right;">0.6009</td>
<td style="text-align: right;">0.5918</td>
<td style="text-align: right;">0.3750</td>
<td style="text-align: right;">0.6970</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rpart</td>
<td style="text-align: right;">0.5881</td>
<td style="text-align: right;">0.6837</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.8636</td>
</tr>
<tr class="even">
<td style="text-align: left;">knn</td>
<td style="text-align: right;">0.5573</td>
<td style="text-align: right;">0.5714</td>
<td style="text-align: right;">0.5312</td>
<td style="text-align: right;">0.5909</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="caso-3-variables-seleccionadas-sin-balanceo" class="level3">
<h3 class="anchored" data-anchor-id="caso-3-variables-seleccionadas-sin-balanceo">Caso 3: Variables Seleccionadas / Sin Balanceo</h3>
<p>En el Caso 3 (Variables Seleccionadas / Sin Balanceo), el modelo GLM obtuvo el mayor AUC (0.6671), seguido por GBM (0.6615). A pesar de la selección de variables, la sensibilidad (capacidad para detectar la clase positiva, que en este caso son los estudiantes que reprueban) sigue siendo baja, con un valor de 0.3750 para GLM y 0.3125 para GBM, lo que indica que el modelo no está capturando bien a los estudiantes en riesgo. La especificidad, en cambio, es alta (0.8485 para GLM), lo que significa que el modelo es bueno para identificar a los estudiantes que pasarán.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "--- TABLA DE RENDIMIENTO: CASO 3 ---"</code></pre>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resultados: Variables Seleccionadas / Sin Balanceo</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">AUC</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Sensitivity</th>
<th style="text-align: right;">Specificity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">glm</td>
<td style="text-align: right;">0.6671</td>
<td style="text-align: right;">0.6939</td>
<td style="text-align: right;">0.3750</td>
<td style="text-align: right;">0.8485</td>
</tr>
<tr class="even">
<td style="text-align: left;">gbm</td>
<td style="text-align: right;">0.6615</td>
<td style="text-align: right;">0.6224</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.7727</td>
</tr>
<tr class="odd">
<td style="text-align: left;">svmRadial</td>
<td style="text-align: right;">0.6520</td>
<td style="text-align: right;">0.6633</td>
<td style="text-align: right;">0.3438</td>
<td style="text-align: right;">0.8182</td>
</tr>
<tr class="even">
<td style="text-align: left;">knn</td>
<td style="text-align: right;">0.6302</td>
<td style="text-align: right;">0.6224</td>
<td style="text-align: right;">0.2500</td>
<td style="text-align: right;">0.8030</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rf</td>
<td style="text-align: right;">0.6274</td>
<td style="text-align: right;">0.6327</td>
<td style="text-align: right;">0.3438</td>
<td style="text-align: right;">0.7727</td>
</tr>
<tr class="even">
<td style="text-align: left;">rpart</td>
<td style="text-align: right;">0.6009</td>
<td style="text-align: right;">0.6939</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.8788</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="caso-4-variables-seleccionadas-con-balanceo" class="level3">
<h3 class="anchored" data-anchor-id="caso-4-variables-seleccionadas-con-balanceo">Caso 4: Variables Seleccionadas / Con Balanceo</h3>
<p>La combinación de selección de variables y balanceo produjo los mejores resultados para la identificación de estudiantes en riesgo. El modelo GLM alcanzó el mejor AUC del estudio (0.6806), seguido muy de cerca por SVM Radial (0.6802). Además, el balanceo permitió que la Sensibilidad alcanzara niveles significativamente más altos, con el modelo KNN logrando la mayor detección de casos en riesgo (0.6250), lo que confirma que tanto la reducción de dimensionalidad como el balanceo de clases son esenciales para construir modelos que realmente puedan identificar a los estudiantes que necesitan intervención.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "--- TABLA DE RENDIMIENTO: CASO 4 (OPTIMIZADO) ---"</code></pre>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resultados: Variables Seleccionadas / Con Balanceo (Up-Sampling)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">AUC</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Sensitivity</th>
<th style="text-align: right;">Specificity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">glm</td>
<td style="text-align: right;">0.6806</td>
<td style="text-align: right;">0.6327</td>
<td style="text-align: right;">0.5312</td>
<td style="text-align: right;">0.6818</td>
</tr>
<tr class="even">
<td style="text-align: left;">svmRadial</td>
<td style="text-align: right;">0.6802</td>
<td style="text-align: right;">0.6531</td>
<td style="text-align: right;">0.5938</td>
<td style="text-align: right;">0.6818</td>
</tr>
<tr class="odd">
<td style="text-align: left;">knn</td>
<td style="text-align: right;">0.6683</td>
<td style="text-align: right;">0.6122</td>
<td style="text-align: right;">0.6250</td>
<td style="text-align: right;">0.6061</td>
</tr>
<tr class="even">
<td style="text-align: left;">gbm</td>
<td style="text-align: right;">0.6584</td>
<td style="text-align: right;">0.6429</td>
<td style="text-align: right;">0.5000</td>
<td style="text-align: right;">0.7121</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rf</td>
<td style="text-align: right;">0.6546</td>
<td style="text-align: right;">0.6429</td>
<td style="text-align: right;">0.4375</td>
<td style="text-align: right;">0.7424</td>
</tr>
<tr class="even">
<td style="text-align: left;">rpart</td>
<td style="text-align: right;">0.5743</td>
<td style="text-align: right;">0.5918</td>
<td style="text-align: right;">0.5000</td>
<td style="text-align: right;">0.6364</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="análisis-comparativo-del-desempeño-de-los-modelos" class="level2">
<h2 class="anchored" data-anchor-id="análisis-comparativo-del-desempeño-de-los-modelos">4.Análisis comparativo del desempeño de los modelos</h2>
<section id="resultados-de-los-modelos" class="level3">
<h3 class="anchored" data-anchor-id="resultados-de-los-modelos">Resultados de los modelos</h3>
<p>En esta sección, se combinan las tablas de rendimiento de cada caso (Todas las variables vs.&nbsp;Seleccionadas / Sin Balanceo vs.&nbsp;Con Balanceo) en un único conjunto de datos. Esta integración permitirá realizar una comparación directa y ordenada por AUC para determinar, con evidencia métrica, cuál fue la estrategia más efectiva para predecir el rendimiento estudiantil.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Comparación de los 4 Casos</caption>
<colgroup>
<col style="width: 28%">
<col style="width: 16%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Case</th>
<th style="text-align: left;">Model</th>
<th style="text-align: right;">AUC</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Sensitivity</th>
<th style="text-align: right;">Specificity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Case 1: All/NoBal</td>
<td style="text-align: left;">gbm</td>
<td style="text-align: right;">0.6425</td>
<td style="text-align: right;">0.6327</td>
<td style="text-align: right;">0.2500</td>
<td style="text-align: right;">0.8182</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 1: All/NoBal</td>
<td style="text-align: left;">glm</td>
<td style="text-align: right;">0.6335</td>
<td style="text-align: right;">0.6122</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.7576</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 1: All/NoBal</td>
<td style="text-align: left;">rf</td>
<td style="text-align: right;">0.6127</td>
<td style="text-align: right;">0.7143</td>
<td style="text-align: right;">0.4062</td>
<td style="text-align: right;">0.8636</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 1: All/NoBal</td>
<td style="text-align: left;">rpart</td>
<td style="text-align: right;">0.6125</td>
<td style="text-align: right;">0.6429</td>
<td style="text-align: right;">0.3750</td>
<td style="text-align: right;">0.7727</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 1: All/NoBal</td>
<td style="text-align: left;">svmRadial</td>
<td style="text-align: right;">0.5909</td>
<td style="text-align: right;">0.7041</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.8939</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 1: All/NoBal</td>
<td style="text-align: left;">naive_bayes</td>
<td style="text-align: right;">0.5421</td>
<td style="text-align: right;">0.5918</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.7273</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 1: All/NoBal</td>
<td style="text-align: left;">knn</td>
<td style="text-align: right;">0.5386</td>
<td style="text-align: right;">0.6327</td>
<td style="text-align: right;">0.2500</td>
<td style="text-align: right;">0.8182</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 2: All/Balanced</td>
<td style="text-align: left;">glm</td>
<td style="text-align: right;">0.6316</td>
<td style="text-align: right;">0.6122</td>
<td style="text-align: right;">0.5000</td>
<td style="text-align: right;">0.6667</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 2: All/Balanced</td>
<td style="text-align: left;">gbm</td>
<td style="text-align: right;">0.6259</td>
<td style="text-align: right;">0.6327</td>
<td style="text-align: right;">0.4062</td>
<td style="text-align: right;">0.7424</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 2: All/Balanced</td>
<td style="text-align: left;">rf</td>
<td style="text-align: right;">0.6120</td>
<td style="text-align: right;">0.6633</td>
<td style="text-align: right;">0.4062</td>
<td style="text-align: right;">0.7879</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 2: All/Balanced</td>
<td style="text-align: left;">svmRadial</td>
<td style="text-align: right;">0.6009</td>
<td style="text-align: right;">0.5918</td>
<td style="text-align: right;">0.3750</td>
<td style="text-align: right;">0.6970</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 2: All/Balanced</td>
<td style="text-align: left;">rpart</td>
<td style="text-align: right;">0.5881</td>
<td style="text-align: right;">0.6837</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.8636</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 2: All/Balanced</td>
<td style="text-align: left;">knn</td>
<td style="text-align: right;">0.5573</td>
<td style="text-align: right;">0.5714</td>
<td style="text-align: right;">0.5312</td>
<td style="text-align: right;">0.5909</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 3: Sel/NoBal</td>
<td style="text-align: left;">glm</td>
<td style="text-align: right;">0.6671</td>
<td style="text-align: right;">0.6939</td>
<td style="text-align: right;">0.3750</td>
<td style="text-align: right;">0.8485</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 3: Sel/NoBal</td>
<td style="text-align: left;">gbm</td>
<td style="text-align: right;">0.6615</td>
<td style="text-align: right;">0.6224</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.7727</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 3: Sel/NoBal</td>
<td style="text-align: left;">svmRadial</td>
<td style="text-align: right;">0.6520</td>
<td style="text-align: right;">0.6633</td>
<td style="text-align: right;">0.3438</td>
<td style="text-align: right;">0.8182</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 3: Sel/NoBal</td>
<td style="text-align: left;">knn</td>
<td style="text-align: right;">0.6302</td>
<td style="text-align: right;">0.6224</td>
<td style="text-align: right;">0.2500</td>
<td style="text-align: right;">0.8030</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 3: Sel/NoBal</td>
<td style="text-align: left;">rf</td>
<td style="text-align: right;">0.6274</td>
<td style="text-align: right;">0.6327</td>
<td style="text-align: right;">0.3438</td>
<td style="text-align: right;">0.7727</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 3: Sel/NoBal</td>
<td style="text-align: left;">rpart</td>
<td style="text-align: right;">0.6009</td>
<td style="text-align: right;">0.6939</td>
<td style="text-align: right;">0.3125</td>
<td style="text-align: right;">0.8788</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 4: Sel/Balanced</td>
<td style="text-align: left;">glm</td>
<td style="text-align: right;">0.6806</td>
<td style="text-align: right;">0.6327</td>
<td style="text-align: right;">0.5312</td>
<td style="text-align: right;">0.6818</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 4: Sel/Balanced</td>
<td style="text-align: left;">svmRadial</td>
<td style="text-align: right;">0.6802</td>
<td style="text-align: right;">0.6531</td>
<td style="text-align: right;">0.5938</td>
<td style="text-align: right;">0.6818</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 4: Sel/Balanced</td>
<td style="text-align: left;">knn</td>
<td style="text-align: right;">0.6683</td>
<td style="text-align: right;">0.6122</td>
<td style="text-align: right;">0.6250</td>
<td style="text-align: right;">0.6061</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 4: Sel/Balanced</td>
<td style="text-align: left;">gbm</td>
<td style="text-align: right;">0.6584</td>
<td style="text-align: right;">0.6429</td>
<td style="text-align: right;">0.5000</td>
<td style="text-align: right;">0.7121</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 4: Sel/Balanced</td>
<td style="text-align: left;">rf</td>
<td style="text-align: right;">0.6546</td>
<td style="text-align: right;">0.6429</td>
<td style="text-align: right;">0.4375</td>
<td style="text-align: right;">0.7424</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 4: Sel/Balanced</td>
<td style="text-align: left;">rpart</td>
<td style="text-align: right;">0.5743</td>
<td style="text-align: right;">0.5918</td>
<td style="text-align: right;">0.5000</td>
<td style="text-align: right;">0.6364</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="ranking-de-los-mejores-modelos" class="level3">
<h3 class="anchored" data-anchor-id="ranking-de-los-mejores-modelos">Ranking de los mejores modelos</h3>
<p>El objetivo más importante de este estudio es identificar a los estudiantes en riesgo de reprobación. En este contexto, el costo de no detectar a un estudiante que va a reprobar (Falso Negativo) es mucho mayor que el costo de intervenir innecesariamente con un estudiante que iba a aprobar (Falso Positivo). Por lo tanto, priorizamos la Sensibilidad sobre otras métricas.</p>
<p>Analizando los resultados del Caso 4 (Selección + Balanceo), presentamos las mejores opciones bajo este criterio:</p>
<section id="la-opción-de-máxima-seguridad-knn-caso-4" class="level4">
<h4 class="anchored" data-anchor-id="la-opción-de-máxima-seguridad-knn-caso-4">La Opción de Máxima Seguridad: KNN (Caso 4)</h4>
<p>Si la política institucional es “ningún estudiante en riesgo debe pasar desapercibido”, el K-Vecinos Más Cercanos (KNN) es la elección correcta.</p>
<p>Desempeño: Logró la Sensibilidad más alta del estudio (0.6250). Esto significa que es capaz de detectar el 62.5% de los casos de reprobación, superando a todos los demás algoritmos.</p>
<p>La Contrapartida: Su Especificidad es del 0.6061. Esto implica que habrá 39.4% de “falsas alarmas” (estudiantes que el modelo marca en riesgo pero que aprobarían), lo cual requerirá un monto significativo de recursos docentes para intervenciones preventivas o no necesarias, pero garantiza la mayor cobertura de seguridad.</p>
</section>
<section id="el-balance-óptimo-svm-radial-caso-4" class="level4">
<h4 class="anchored" data-anchor-id="el-balance-óptimo-svm-radial-caso-4">El Balance Óptimo: SVM Radial (Caso 4)</h4>
<p>Si se busca un equilibrio donde se mantenga una alta detección de riesgo sin generar excesivas falsas alarmas, el SVM Radial es la mejor alternativa técnica.</p>
<p>Desempeño: Ofrece una Sensibilidad muy competitiva de 0.5938 (muy cerca del KNN) pero mejora significativamente la Especificidad a 0.6818.</p>
<p>Ventaja: Detecta casi la misma cantidad de estudiantes en riesgo que el KNN, pero se equivoca menos al clasificar a los estudiantes seguros, ofreciendo una gestión más eficiente de los recursos de tutoría.</p>
</section>
<section id="alternativa-destacada-por-auc-glm-caso-4" class="level4">
<h4 class="anchored" data-anchor-id="alternativa-destacada-por-auc-glm-caso-4">Alternativa Destacada por AUC: GLM (Caso 4)</h4>
<p>Aunque el Modelo Lineal Generalizado obtuvo el mejor AUC global (0.6806), su Sensibilidad de 0.5312 lo hace menos apto para este objetivo específico. Deja pasar a casi la mitad de los estudiantes en riesgo sin detectarlos, por lo que se descarta frente a la prioridad de seguridad del KNN o el SVM.</p>
</section>
</section>
</section>
</section>
<section id="hallazgos-y-conclusion-del-proyecto" class="level1">
<h1>Hallazgos y conclusion del proyecto</h1>
<section id="hallazgos" class="level2">
<h2 class="anchored" data-anchor-id="hallazgos">Hallazgos</h2>
<p>Tras ejecutar el análisis completo, se han identificado los factores que más influyeron en el rendimiento estudiantil y los modelos que mejor logran predecirlo.</p>
<section id="variables-influyentes-en-el-éxito-o-fracaso-académico-en-matemática" class="level3">
<h3 class="anchored" data-anchor-id="variables-influyentes-en-el-éxito-o-fracaso-académico-en-matemática">Variables influyentes en el Éxito o Fracaso académico en matemática</h3>
<p>A través del método de consenso algorítmico (donde Chi-Cuadrado, Boruta y RFE votaron por las variables más fuertes), se determinó que el rendimiento de un estudiante no depende de todas las variables recolectadas, sino fundamentalmente de estas cinco:</p>
<ol type="a">
<li><p><strong>failures (Historial de Reprobación):</strong> Es el predictor más fuerte. El historial académico pasado es el mejor indicador del futuro; un estudiante que ya ha reprobado anteriormente tiene un riesgo significativamente mayor.</p></li>
<li><p><strong>higher (Aspiración Superior):</strong> La motivación intrínseca juega un papel importante. Los estudiantes que desean cursar educación superior muestran un perfil de aprobación mucho más sólido.</p></li>
<li><p><strong>absences (Ausentismo):</strong> La asistencia regular es fundamental. Un número elevado de faltas correlaciona directamente con la probabilidad de reprobar.</p></li>
<li><p><strong>goout (Vida Social):</strong> La frecuencia con la que el estudiante sale con amigos impacta su rendimiento, probablemente restando tiempo de estudio si es excesiva.</p></li>
<li><p><strong>schoolsup (Apoyo Educativo Extra):</strong> Curiosamente, recibir apoyo extra es un indicador de riesgo, ya que generalmente se asigna a estudiantes que ya están teniendo dificultades académicas.</p></li>
</ol>
</section>
<section id="resumen-de-los-modelos-más-eficaces" class="level3">
<h3 class="anchored" data-anchor-id="resumen-de-los-modelos-más-eficaces">Resumen de los Modelos Más Eficaces</h3>
<p>Basándose en el escenario optimizado (Caso 4: Variables Seleccionadas + Balanceo), estos son los tres modelos que mostraron el mejor desempeño para la detección de estudiantes en riesgo:</p>
<ul>
<li><p><strong>KNN (K-Vecinos Más Cercanos):</strong> Fue el mejor detector de riesgo. Si el objetivo es identificar a la mayor cantidad posible de estudiantes vulnerables (alta Sensibilidad), este es el algoritmo ganador.</p></li>
<li><p><strong>SVM Radial (Máquina de Vectores de Soporte):</strong> Se destacó como la opción equilibrada. Ofrece un compromiso sólido entre detectar estudiantes en riesgo y no generar demasiadas falsas alarmas.</p></li>
<li><p><strong>GLM (Regresión Logística):</strong> Sobresalió por su estabilidad global. Obtuvo el puntaje más alto en AUC, lo que significa que es matemáticamente el más robusto para separar las clases de “Pasa” y “Reprueba” en general, aunque es menos agresivo detectando el riesgo puro.</p></li>
</ul>
</section>
</section>
<section id="conclusión" class="level2">
<h2 class="anchored" data-anchor-id="conclusión">Conclusión</h2>
<p>En conclusión, para cumplir con el objetivo de maximizar la detección de estudiantes en riesgo, se recomienda implementar el modelo KNN del Caso 4 (selección de variables y balanceo de clases). Aunque sacrifica precisión global, es la herramienta más efectiva disponible en este análisis para asegurar que la mayor cantidad posible de estudiantes vulnerables reciban atención temprana.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>